<a href="https://colab.research.google.com/github/romeuqf/Alura/blob/main/Introdu%C3%A7%C3%A3o_a_Machine_Learning_Classifica%C3%A7%C3%A3o_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
uri = "https://gist.githubusercontent.com/guilhermesilveira/2d2efa37d66b6c84a722ea627a897ced/raw/10968b997d885cbded1c92938c7a9912ba41c615/tracking.csv"
mapa= {'home':'principal',
       'how_it_works':'como_funciona',
       'contact':'contato',
       'bought':'comprou'}
base = pd.read_csv(uri)
base.rename(columns=mapa,inplace=True)
base.head()

   principal  como_funciona  contato  comprou
0          1              1        0        0
1          1              1        0        0
2          1              1        0        0
3          1              1        0        0
4          1              1        0        0

In [ ]:
x = base[['principal','como_funciona','contato']]
x.head()

   principal  como_funciona  contato
0          1              1        0
1          1              1        0
2          1              1        0
3          1              1        0
4          1              1        0

In [ ]:
y = base['comprou']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: comprou, dtype: int64

In [ ]:
base.shape

(99, 4)

In [ ]:
treino_x = x[:75]
treino_y = y[:75]
teste_x = x[75:]
teste_y = y[75:]

In [ ]:
print('Treinaremos com %d e testaremos com %d elementos' %(len(treino_x),len(teste_x)))

Treinaremos com 75 e testaremos com 24 elementos

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

In [ ]:
modelo = LinearSVC()
modelo.fit(treino_x,treino_y)

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(

LinearSVC()

In [ ]:
previsoes = modelo.predict(teste_x)
previsoes

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0])

In [ ]:
acuracio = accuracy_score(teste_y,previsoes)*100
print('A acuracia foi %.2f%%' %acuracio)

A acuracia foi 95.83%

Separando Treino e Teste com Biblioteca

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

SEED = 20

treino_x, teste_x, treino_y, teste_y = train_test_split(x,y,random_state=SEED, test_size=0.25)
print(treino_x.shape)
print(teste_x.shape)
print('Treinaremos com %d e testaremos com %d elementos' %(len(treino_x),len(teste_x)))
modelo = LinearSVC()
modelo.fit(treino_x,treino_y)
previsoes = modelo.predict(teste_x)
acuracio = accuracy_score(teste_y,previsoes)*100
print('A acuracia foi %.2f%%' %acuracio)

(74, 3)
(25, 3)
Treinaremos com 74 e testaremos com 25 elementos
A acuracia foi 96.00%

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(

In [ ]:
treino_y.value_counts()

comprou
0    47
1    27
Name: count, dtype: int64

In [ ]:
teste_y.value_counts()

comprou
0    19
1     6
Name: count, dtype: int64

In [ ]:
47/27

1.7407407407407407

In [ ]:
19/6

3.1666666666666665

Definir proporcionalidade

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

SEED = 20

treino_x, teste_x, treino_y, teste_y = train_test_split(x,y,random_state=SEED, test_size=0.25, stratify=y)
print(treino_x.shape)
print(teste_x.shape)
print('Treinaremos com %d e testaremos com %d elementos' %(len(treino_x),len(teste_x)))
modelo = LinearSVC()
modelo.fit(treino_x,treino_y)
previsoes = modelo.predict(teste_x)
acuracio = accuracy_score(teste_y,previsoes)*100
print('A acuracia foi %.2f%%' %acuracio)

(74, 3)
(25, 3)
Treinaremos com 74 e testaremos com 25 elementos
A acuracia foi 96.00%

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(

In [ ]:
print(treino_y.value_counts())
print(teste_y.value_counts())

comprou
0    49
1    25
Name: count, dtype: int64
comprou
0    17
1     8
Name: count, dtype: int64

In [ ]:
print(49/25)
print(17/8)

1.96
2.125